# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  rootDir: "my-app"
  buildDir: "$(rootDir)/build"
  REACT_APP_DRIVE_KEY: $(APP_KEY)

steps:
  - bash: |
      echo "API is $(APP_KEY)"
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
    env:
        REACT_APP_DRIVE_KEY: $(APP_KEY)
  - script: |
      cd $(rootDir)
      npm install
      npm run build
      cd ..
    displayName: 'npm install and build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(buildDir)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'